title: Liquid Templating Engine
description: "Liquid is a template language and accompanying rendering engine. It is built for security, so is perfect for rendering custom templates from your users."
repository: https://github.com/Shopify/liquid

# Build settings
baseurl:                /liquid # the subpath of your site, e.g. /blog/
url:                    https://shopify.github.io # the base hostname & protocol for your site
markdown:               redcarpet
redcarpet:
  extensions:           ["with_toc_data", "tables", "disable_indented_code_blocks", "no_intra_emphasis"]
highlighter:            pygments
permalink:              pretty
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gruntfile.js
  - package.json
  - node_modules
keep_files:             ["css"]

# Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
