title: Joko Framework
description: "Framework para aplicaciones web y mobile"
repository: https://github.com/sodep/joko

# Build settings
baseurl:                /joko # the subpath of your site, e.g. /blog/
url:                    https://sodep.github.io # the base hostname & protocol for your site
markdown:               redcarpet
redcarpet:
  extensions:           ["with_toc_data", "tables", "disable_indented_code_blocks", "no_intra_emphasis"]
highlighter:            pygments
permalink:              pretty
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gruntfile.js
  - package.json
  - node_modules
keep_files:             ["css"]

# Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
